### ISSUE TITLE
Problems with MQTTSenderTest.java

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/export-distro#40]
While working on my edgex-core-snap, I ran into a build failure with one the MQTTSenderTest unit test.  The setup() function creates a new MQTTSender instance, which fails on launchpad (where my snap is being built) due to an UnknownHostException.

From my point of view build time (unit) tests should never rely on external services.  Is there a way to annotate this class so that it's not automatically run when building the project?

It also looks like there was additional problems with this class and Jenkins, so the two test functions in the class are currently commented out.

This applies to the latest code (which has been tagged 0.5.0) as well as the Barcelona release.

**Comment by Dunstable** [comment]
Hi, Tony,

Agreed, unit tests should not rely on external services.  The use of an external MQTT broker was probably done more for expediency and minimal code (e.g. quick smoke test) than as a point of philosophy.  Since you looked at the unit tests, you may have noticed these tests are rather minimal.  A proper MQTT unit test needs a mock MQTT broker that would validate what it received and feed that back to the unit test harness  as well as provide mechanisms to send valid and invalid (re: negative testing) messages back.  An external broker may not provide such abilities.  Perhaps Janko can put this on the to-do list?

~Rodney

**Comment by eb-oss** [comment]
Closing issue; project is being archived.
